CRMP/CRMP/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

crmApp/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.signin,name='signin'),
    path('index',views.index,name='index'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('maps',views.maps,name='maps'),
    path('profile/<str:user_name>',views.profile,name='profile'),
    path('show_clients_cards',views.show_clients_cards,name='show_clients_cards'),    
    path('show_clients',views.show_clients,name='show_clients'),
    path('create_client',views.create_client,name='create_client'),
    path('logout',views.logout,name='logout'),
    path('show_tasks',views.show_tasks,name='show_tasks'),
    path('show_client_details/<int:pk>',views.show_client_details,name='show_client_details'),
    path('create_task',views.create_task,name='create_task'),
    path('show_payments',views.show_payments,name='show_payments'),
    path('update_client/<int:pk>',views.update_client,name='update_client'),
    path('update_client/updated/<int:pk>',views.updated,name='updated'),
    path('update_task/<int:pk>',views.update_task,name='update_task'),
    path('update_task/updated_task/<int:pk>',views.updated_task,name='updated_task'),
    path('update_payment/<int:pk>',views.update_payment,name='update_payment'),
    path('update_payment/updated_payment/<int:pk>',views.updated_payment,name='updated_payment'),
    path('show_task_details/<int:pk>',views.show_task_details,name='show_task_details'),
    path('show_task_details/upload_new_brief/<int:pk>/<int:id>',views.upload_new_brief,name='upload_new_brief'),
    path('show_task_details/delete_brief/<int:pk>/<int:id>',views.delete_brief,name='delete_brief'),
    path('delete_task/<int:pk>',views.delete_task,name='delete_task'),
    path('show_employee_cards',views.show_employee_cards,name='show_employee_cards'), 
    path('show_employees',views.show_employees,name='show_employees'),
    path('create_employee',views.create_employee,name='create_employee'),
    path('show_employee_details/<int:pk>',views.show_employee_details,name='show_employee_details'),
    path('update_employee/<int:pk>',views.update_employee,name='update_employee'),
    path('update_employee/updated_employee/<int:pk>',views.updated_employee,name='updated_employee'),
    path('delete_employee/<int:pk>',views.delete_employee,name='delete_employee'),
    path('assign_task/<str:user_name>',views.assign_task,name='assign_task'),
    path('show_employee_details/assigned_task_details/<int:pk>',views.assigned_task_details,name='assigned_task_details'),
    path('show_employee_details/assigned_task_details/upload_solution/<int:pk>/<int:id>',views.upload_solution,name='upload_solution'),
    path('show_employee_details/assigned_task_details/delete_solution/<int:pk>/<int:id>',views.delete_solution,name='delete_solution'),
    path('settings',views.settings,name='settings'),
    path('pages-profile/<int:pk>',views.update_user,name='update_user'),    
    path('roles_permissions',views.roles_permissions,name='roles_permissions'),    
    path('create_role',views.create_role,name='create_role'),
    path('show_edit_role/<int:pk>',views.show_edit_role,name='show_edit_role'),
    path('show_edit_role/updated_role',views.updated_role,name='updated_role'),
    path('delete_role/<int:pk>',views.delete_role,name='delete_role'),
    path('user_details',views.user_details,name='user_details'),
    path('create_user',views.create_user,name='create_user'),
    path('update_user/<int:pk>',views.update_user,name='update_user'),
    path('update_user/updated_user/<int:pk>',views.updated_user,name='updated_user'),
    path('delete_user/<int:pk>',views.delete_user,name='delete_user'),
    path('show_employee_details/assigned_task_details/task_complete/<int:pk>/<str:user_name>/<int:id>',views.task_complete,name='task_complete'),
    path('show_particular_task/<str:pk>',views.show_particular_task,name='show_particular_task'),
    path('show_task_details/upload_new_solution/<int:pk>',views.upload_new_solution,name='upload_new_solution'),
    path('show_task_details/delete_new_solution/<int:pk>/<int:id>',views.delete_new_solution,name='delete_new_solution'),
    path('create_role_group',views.create_role_group,name='create_role_group'),
    path('show_groups/<str:user_name>',views.show_groups,name='show_groups'),
    path('create_group/<str:user_name>',views.create_group,name='create_group'),
    path('show_particular_group/<str:user_name>/<int:pk>',views.show_particular_group,name='show_particular_group'),
    path('remove_member/<str:user_name>/<int:tl_id>/<int:mem_id>',views.remove_member,name='remove_member'),
    path('show_tl_group/<str:user_name>',views.show_tl_group,name='show_tl_group'),
    path('assign_particular_task/<str:user_name>',views.assign_particular_task,name='assign_particular_task'),
    path('create_comment/<str:user_name>/<int:pk>/<str:task_name>',views.create_comment,name='create_comment'),
    path('assigned_comment/<str:user_name>/<int:pk>/<str:task_name>',views.assigned_comment,name='assigned_comment'),
    path('bulk_task_creation',views.bulk_task_creation,name='bulk_task_creation'),
    path('mark_attendance',views.mark_attendance,name='mark_attendance'),
    path('show_attendance',views.show_attendance,name='show_attendance'),
    path('revoke_tasks/<str:user_name>',views.revoke_tasks,name='revoke_tasks'),
    path('show_notifications',views.show_notifications,name='show_notifications'),
    path('mark_read/<int:note_id>',views.mark_read,name='mark_read'),
    path('show_cat/<str:role_names>',views.show_cat,name='show_cat'),
    path('profile_admin/<int:pk>',views.profile_admin,name='profile_admin'),
    path('pay', views.pay, name='pay'),
    path('paymenthandler/', views.paymenthandler, name='paymenthandler'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

crmproject/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
import notifications.urls
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('crmApp.urls')),
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),


crmApp/models.py
from django.db import models
from django.contrib.auth.models import Group

# Create your models here.
class role(models.Model):
    role_name=models.CharField(null = True,max_length=20)


class login(models.Model):
    username= models.CharField(null=False,max_length= 20)
    password = models.CharField(null=False, max_length=20)
    role_id=models.ForeignKey(Group,on_delete=models.CASCADE)
    emp_id = models.ForeignKey("employee",on_delete=models.CASCADE)
    
class employee(models.Model):
    e_name=models.CharField(null=True,max_length=20)
    e_num=models.CharField(null=True,max_length=30)
    e_email=models.CharField(null=True,max_length=50)
    e_address=models.CharField(null=True,max_length=100)
    e_account_no=models.IntegerField()
    e_ifsc= models.CharField(null=True,max_length=20)
    role_id=models.ForeignKey(Group,on_delete=models.CASCADE)


class permission(models.Model):
    permission_name=models.CharField(max_length=20)
    role_id=models.ForeignKey(Group,on_delete=models.CASCADE)

class client(models.Model):
    c_name=models.CharField(null=True,max_length=20)
    c_num=models.CharField(null=True,max_length=30)
    c_email=models.CharField(null=True,max_length=50)
    c_university=models.CharField(null=True,max_length=100)
    c_created_by = models.CharField(max_length=30)

class task(models.Model):
    t_desc=models.CharField(null=True, max_length=100)
    t_name=models.CharField(null=False, max_length=20)
    t_soft=models.DateField(null=True,blank=False)
    t_hard=models.DateField(null=False,blank=False)
    t_wc = models.IntegerField()
    t_amount=models.IntegerField()
    t_currency=models.CharField(null=True,max_length=40)
    t_status = models.CharField(null=True,max_length = 20)
    client_id=models.ForeignKey("client",on_delete=models.CASCADE)
    t_created_by = models.CharField(max_length=30)

class cancelledTask(models.Model):
    ctask_desc=models.CharField(null=False,max_length=100)
    ctask_name = models.CharField(null=False,max_length=50)
    ct_hard=models.DateField(null=False,blank=False)
    ct_wc = models.IntegerField()
    ct_amount = models.IntegerField()
    client_id=models.ForeignKey("client",on_delete=models.DO_NOTHING)

class filesBrief(models.Model):
    f_name = models.CharField(null=False, max_length=20)
    f_desc = models.CharField(null=False,max_length=100)
    f_link = models.FileField(upload_to='upload/documents/')
    task_id=models.ForeignKey("task",on_delete=models.CASCADE)

class solutionFile(models.Model):
    sf_name = models.CharField(null=False, max_length=20)
    sf_desc = models.CharField(null=False, max_length=100)
    sf_wc =   models.IntegerField()
    sf_link = models.CharField(null=False,max_length=100)
    task_id=models.ForeignKey("task",on_delete=models.CASCADE)
   


class payment(models.Model):
    due_amount=models.CharField(null = True , max_length = 10)
    p_status=models.CharField(null=True,max_length=20)
    p_date=models.DateField(null=True,blank=False)
    p_time = models.TimeField(null=True,blank=False)
    task_id=models.ForeignKey("task",on_delete=models.CASCADE)
    p_created_by = models.CharField(max_length=30)


class cancelledBrief(models.Model):
    cbf_name = models.CharField(null=False, max_length=20)
    cbf_desc = models.CharField(null=False,max_length=100)
    cbf_link = models.CharField(null=False,max_length=100)
    task_id=models.ForeignKey("task",on_delete=models.DO_NOTHING)

class assignedTaskTable(models.Model):
    at_desc=models.CharField(null=True, max_length=100)
    at_name=models.CharField(null=False, max_length=20)
    at_soft=models.DateField(null=True,blank=False)
    task_id=models.ForeignKey("task",on_delete=models.CASCADE)
    manager_id=models.ForeignKey("employee",on_delete=models.DO_NOTHING,related_name="manager_id")
    tl_id=models.ForeignKey("employee",on_delete=models.DO_NOTHING,related_name="tl_id")
    expert_id=models.ForeignKey("employee",on_delete=models.DO_NOTHING,related_name="expert_id")

class employeeFileBrief(models.Model):
    efb_name = models.CharField(null=False, max_length=20)
    efb_desc = models.CharField(null=False,max_length=100)
    efb_link = models.FileField(upload_to='upload/documents/')
    task_id=models.ForeignKey("task",on_delete=models.CASCADE)
    emp_id = models.ForeignKey("employee",on_delete=models.CASCADE)

class deletedEmployee(models.Model):
    de_name=models.CharField(null=True,max_length=20)
    de_num=models.IntegerField()
    de_email=models.CharField(null=True,max_length=50)
    de_address=models.CharField(null=True,max_length=100)
    de_account_no=models.IntegerField()
    de_ifsc= models.CharField(null=True,max_length=20)
    tasks = models.IntegerField()
    role_id=models.ForeignKey(Group,on_delete=models.CASCADE)


class grouptable(models.Model):
    tl_emp_id=models.ForeignKey("employee",on_delete=models.CASCADE,related_name="team_lead_id")
    members_emp_id=models.ForeignKey("employee",on_delete=models.CASCADE,related_name="member_ids")

class attendanceTable(models.Model):
    att_employee_id=models.ForeignKey("employee",on_delete=models.DO_NOTHING)
    att_employee_name=models.CharField(max_length=50)
    att_date=models.DateField(null=True)
    att_time=models.TimeField(null=True)
    att_status=models.CharField(max_length=10)


class comments(models.Model):
    from_username=models.CharField(max_length=30,null=True)
    to_username=models.CharField(max_length=30,null=True)
    task_id=models.ForeignKey("task",on_delete=models.CASCADE,null=True)
    task_name=models.CharField(max_length=30,null=True)
    message=models.CharField(max_length=255,null=True)

class UserNotifications(models.Model):
    from_username=models.CharField(max_length=30,null=True)
    to_username=models.CharField(max_length=30,null=True)
    message=models.CharField(max_length=100,null=True)
    m_time=models.CharField(max_length=30,null=True)
    m_status=models.CharField(max_length=30,null=True)

templates/pay.html
{% block content %}
<head>
    <style>
        .center {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>

<div class="center">

    <form class="text-center border border-light p-5" action="success" method="POST">
        {% csrf_token %}

        <p class="h3 mb-3"><i class="fas fa-coffee"></i> Razorpay</p>
        <p class="mb-3">Help us create more videos by donating 500 INR</p>

        <input type="name" name="name" id="name" required class="form-control mb-4" placeholder="Name">

        <!-- RAZORPAY INTEGRATION HERE -->
        <script src="https://checkout.razorpay.com/v1/checkout.js" 
        data-key='rzp_test_mp6XqYww4VvFdI'
            data-amount="50000" data-currency="INR" 
            data-order_id="{{payment.id}}" 
            data-buttontext="Pay with Razorpay"
            data-name="Professional Cipher"
             data-description="Django and Data Science"
            data-image="https://example.com/your_logo.jpg" 
            data-prefill.name="PC" data-prefill.email="pc@studygyaan.com"
            data-theme.color="#F37254"></script>
    </form>

</div>


</div>
{% endblock %}

templates/show_particular_group.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

	<link rel="shortcut icon" href="{% static 'img/icons/icon-48x48.png' %}" />

	<title>CRM</title>

	<link href="{% static 'css/app.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
	{% if user.is_authenticated %}
    {% if perms.crmApp.view_grouptable %}
	<div class="wrapper">
		<nav id="sidebar" class="sidebar">
			<div class="sidebar-content js-simplebar">
				<a class="sidebar-brand" href="{%  url 'dashboard' %}">
          			<span class="align-middle">Requin</span>
					<!-- <img style="width: 100px; height: 40px; padding-left: 30px;" src="{% static 'img/icons/logo3.png' %}"> -->
        		</a>

				<ul class="sidebar-nav">
					<li class="sidebar-header">
						Pages
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="/dashboard">
              				<i class="align-middle" data-feather="sliders"></i> 
							  	<span class="align-middle">Dashboard</span>
            			</a>
					</li>

					<li class="sidebar-item">
						<a class="sidebar-link" href="/profile/{{ user.username }}">
              				<i class="align-middle" data-feather="user"></i> 
								<span class="align-middle">Profile</span>
            			</a>
					</li>
					
					{% if perms.auth.view_user or perms.crmApp.view_role %}
					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'settings' %}">
              				<i class="align-middle" data-feather="settings"></i> 
							  	<span class="align-middle">Settings</span>
            			</a>
					</li>
					{% endif %}
					{% if perms.crmApp.view_client %}
					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'show_clients_cards' %}">
              				<i class="align-middle" data-feather="users"></i> 
							  	<span class="align-middle">Clients</span>
            			</a>
					</li>
					{% endif %}
					
					{% if perms.crmApp.view_task %}
					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'show_tasks' %}">
              				<i class="align-middle" data-feather="book"></i> 
							  	<span class="align-middle">Tasks</span>
            			</a>
					</li>
					{% else %}
					<li class="sidebar-item">
						<a class="sidebar-link" href="/show_particular_task/{{ user.username }}">
              				<i class="align-middle" data-feather="book"></i> 
							  	<span class="align-middle">Tasks</span>
            			</a>
					</li>
					{% endif %}

					{% if perms.crmApp.view_grouptable and perms.crmApp.add_grouptable %}
					<li class="sidebar-item active">
						<a class="sidebar-link" href="/show_groups/{{ user.username }}">
              				<i class="align-middle" data-feather="users"></i> 
							  	<span class="align-middle">Groups</span>
            			</a>
					</li>
					{% elif perms.crmApp.view_grouptable %}
					<li class="sidebar-item active">
						<a class="sidebar-link" href="/show_tl_group/{{ user.username }}">
              				<i class="align-middle" data-feather="users"></i> 
							  	<span class="align-middle">My Group</span>
            			</a>
					</li>
					{% endif %}
					
					{% if perms.crmApp.view_payment %}
					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'show_payments' %}">
              				<i class="align-middle" data-feather="dollar-sign"></i> 
							  	<span class="align-middle">Payments</span>
            			</a>
					</li>
					{% endif %}
					{% if perms.crmApp.view_employee %}
					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'show_employee_cards' %}">
              				<i class="align-middle" data-feather="slack"></i> 
							  	<span class="align-middle">Employees</span>
            			</a>
					</li>
					{% endif %}
					{% if perms.crmApp.view_attendance_table %}
					<li class="sidebar-item">
						<a class="sidebar-link" href="{% url 'show_attendance' %}">
              				<i class="align-middle" data-feather="activity"></i> 
							  	<span class="align-middle">Attendance</span>
            			</a>
					</li>
					{% endif %}


					<li class="sidebar-item">
						<a class="sidebar-link" href="/maps">
              				<i class="align-middle" data-feather="map"></i> 
							  	<span class="align-middle">Maps</span>
            			</a>
					</li>
				</ul>
			</div>
		</nav>

		<div class="main">
			<nav class="navbar navbar-expand navbar-light navbar-bg">
				<a class="sidebar-toggle d-flex">
          			<i class="hamburger align-self-center"></i>
        		</a>

				<form class="d-none d-sm-inline-block">
					<div class="input-group input-group-navbar">
						<input type="text" class="form-control" placeholder="Search…" aria-label="Search">
						<button class="btn" type="button">
              				<i class="align-middle" data-feather="search"></i>
            			</button>
					</div>
				</form>

				<div class="navbar-collapse collapse">
					<ul class="navbar-nav navbar-align">

			<!-- ====================================Notification Bell icon ================================== -->
					
			<li class="nav-item dropdown">
				<a class="nav-icon dropdown-toggle" href="#" id="alertsDropdown" data-toggle="dropdown">
					<div class="position-relative">
						<i class="align-middle" data-feather="bell"></i>
						<span id="indicator" class="indicator"></span>
					</div>
				</a>
				<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right py-0" aria-labelledby="alertsDropdown">

					<div class="dropdown-menu-header">
						 Notifications
					</div>

					<div id="main_div" class="list-group">
						

					</div>
				</div>
			</li>

		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script>
			function lw(){

				$.ajax({
					data: $(this).serialize(), // get the form data
					url: "{% url 'show_notifications' %}",
					// on success
					success: function (response) {

						document.getElementById("indicator").innerHTML = response.counts
						document.getElementById("main_div").innerHTML = ""
						for (let i = 0; i < response.all_users.length; i++) {
							
							var row_div = document.createElement("div")
							var row_id = "row_div"+i;
							row_div.setAttribute("id",row_id);
							document.getElementById("main_div").appendChild(row_div)
							document.getElementById(row_id).classList.remove("row");
							document.getElementById(row_id).classList.remove("g-0");
							document.getElementById(row_id).classList.remove("align-items-center");
							document.getElementById(row_id).className += "row";
							document.getElementById(row_id).className += " g-0";
							document.getElementById(row_id).className += " align-items-center";

							var col_div2 = document.createElement("div")
							var col_id2 = "col_div2_"+i;
							col_div2.setAttribute("id",col_id2);
							document.getElementById(row_id).appendChild(col_div2)
							document.getElementById(col_id2).classList.remove("col");
							document.getElementById(col_id2).classList.remove("align-items-center");
							document.getElementById(col_id2).className += "col";
							document.getElementById(col_id2).className += " align-items-center";
							document.getElementById(col_id2).style.paddingLeft = "20px";

							var btn = document.createElement("P");
							var ids = "id"+i;
							btn.setAttribute("id", ids);
							document.getElementById(col_id2).appendChild(btn);
							document.getElementById(ids).classList.remove("text-dark");
							document.getElementById(ids).className += "text-dark";

							var btn1 = document.createElement("P");
							var idss = "ids"+i;
							btn1.setAttribute("id", idss);
							document.getElementById(col_id2).appendChild(btn1);
							document.getElementById(idss).classList.remove("text-muted");
							document.getElementById(idss).className += "text-muted";

							document.getElementById(ids).innerHTML=""
							document.getElementById(idss).innerHTML=""

							document.getElementById(ids).innerHTML = response.all_users[i]['fields']['message']

							document.getElementById(idss).innerHTML = "At: "+ response.all_users[i]['fields']['m_time']

							var links = document.createElement("A");
							links.innerHTML = "     Mark as Read";
							links.setAttribute("href","javascript:mark("+response.all_users[i]['pk']+");")
							var link_id = "mark_link"+i;
							links.setAttribute("id",link_id)
							var req_link = "javascript:mark("+response.all_users[i]['pk']+");"
				
							document.getElementById(idss).appendChild(links);

						}

					},
					
					error: function (response) {
						
						console.log(response.responseJSON.errors)
					}
				});

				return false;
			}
		</script>

		<script>

			lw();
			setInterval(function(){	lw(); },5000);

		</script>

		<script>
		function mark(pk_id){
			$.ajax({
					data: $(this).serialize(), // get the form data
					url: "/mark_read/"+pk_id,
					// on success
					success: function (response) {
						
						if (response.marked == true) {
							
							alert("Notification Read");
							
						}
						else {

							alert("Failure");
						}

					},
					// on error
					error: function (response) {
						// alert the error if any error occured
						console.log(response.responseJSON.errors)
					}
				});

		}
		</script>

<!-- ====================================Notification Bell icon Stops ================================== -->
						
						<li class="nav-item dropdown">
							<a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-toggle="dropdown">
                				<i class="align-middle" data-feather="settings"></i>
              				</a>
							  
							<a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-toggle="dropdown">{{ user.username }}&nbsp;
                				<span class="text-dark" data-feather="user">{{user.username}}</span>	
              				</a>
							  
							<div class="dropdown-menu dropdown-menu-right">
								<a class="dropdown-item" href="pages-profile.html"><i class="align-middle mr-1" data-feather="user"></i> Profile</a>
								<a class="dropdown-item" href="#"><i class="align-middle mr-1" data-feather="pie-chart"></i> Analytics</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="pages-settings.html"><i class="align-middle mr-1" data-feather="settings"></i> Settings & Privacy</a>
								<a class="dropdown-item" href="#"><i class="align-middle mr-1" data-feather="help-circle"></i> Help Center</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
							</div>
						</li>
					</ul>
				</div>
			</nav>


<!-- ==============================================Group Start Here===================================== -->
			{% for i in em_tl %}
			<main class="content">
				<div class="container-fluid p-0">
					<div class="col-md-12">
                        <div class="card">
							<div class="card-header">
								
								<h1 class="h3 mb-3"><strong>{{ i.e_name }}'s Group</strong></h1>
								
							</div>
							<div class="card-body">
								<div class=" mb-3">
									<h4>Group Members:</h4>
								</div>
							</div>
							<div class="card-body">
								<div class=" mb-3">
									{% for j in group_details %}
									
									<div class="form-check">
										<input class="form-check-input" type="checkbox" value="{{ j.members_emp_id.pk }}" name="member_checks" id="flexCheckDefault" checked>
										<div class="row">
											<label class="form-check-label col-md-6" style="width:100%">
												<h3 style="display:inline;">{{ j.members_emp_id.e_name }}</h3>
											</label>
											{% if perms.crmApp.delete_grouptable %}
											<label class="form-check" style="display:inline; text-align:right;"><a href="/remove_member/{{ user.username }}/{{ i.id }}/{{ j.members_emp_id.id }}" style="text-decoration:none;" onclick='return confirm("Are you sure you want to remove {{ j.members_emp_id.e_name }} from {{ i.e_name }} group")'>- Remove</a></label>
											{% endif %}
											<br><br>
										</div>
									</div>
									
									{% endfor %}
								</div>
							</div>
						</div>
					</div>
				</div>
				{% if perms.crmApp.view_grouptable %}
				<div>
					<a class="btn-2 " type="button" onclick="history.back()"  style="padding: 0,0,0,0;">
						<div class="text">Go Back</div>
					</a>
				</div>
				{% endif %}
			</main>
			{% endfor %}

						
<!-- ==============================================Group Stops Here===================================== -->	

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="{% static 'js/app.js' %}"></script>

  {% else %}
 	<h1>You are not Authorized to view this page</h1>
  {% endif %}

{% else %}
<h1>Please Login to Continue. <a href="{% url 'index' %}">Login</a></h1>
{% endif %}
</body>

</html>